---
- hosts: localhost

  vars:
    fedora_version: "31"
    good_software:
      - chromium
      - discord
      - gnome-tweak-tool
      - telegram-desktop
      - kolourpaint
      - VirtualBox
      - git
      - vim 
    useless_software:
      - Cheese

  vars_files:
    - files/main.yml

  roles:
    - { role: packages, become: yes}
    - { role: keys}
    - { role: vimsetup}
    - { role: http, become: yes}




