---
  - name: dnf update
    dnf:
      name: "*"
      state: latest

  - name: install rpmfusion
    shell: "sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y"

  - name: install custom software
    dnf:
      name: "{{ item }}"
    with_items: "{{ good_software }}"
    become: true
  - name: remove useless software
    dnf:
      name: "{{ item }}"
      state: absent
    with_items: "{{ useless_software }}"
    become: true
