---
  - name: dnf update
    dnf:
      name: "*"
      state: latest
  - name: install rpmfusion
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
  - name: install custom software
    dnf:
      name: "{{ item }}"
    with_items: "{{ good_software }}"
  - name: remove useless software
    dnf:
      name: "{{ item }}"
      state: absent
    with_items: "{{ useless_software }}"
